### ISSUE TITLE
GTCEu Modern TODO-List

### ISSUE THREAD

**Issue by Yefancy** [GregTechCEu/GregTech-Modern#125]
### machines

- [x] Hi-Amp Transformer
- [x] Charger
- [x] Diode
- [x] Fisher
- [x] ItemCollector
- [ ] MagicEnergy
- [x] Miner
- [x] BlockBreaker
- [x] WorldAccelerate

### multiblocks

- [x] Cleanroom
- [x] LargeTurbine
- [x] LargeCombustionEngine
- [x] FluidDrill
- [x] LargeMiner
- [x] MultiSmelter
- [x] ProcessingArray (I will do it later, with features)

### parts

- [x] MaintenanceHatch
- [x] RotorHolder

### covers
....

### items

- [x] prospector
- [x] #140
....

### misc

- [x] Bedrock Fluids
- [x] Rework Machine UIs
- [ ] Fancy Effects
- [ ] More Sounds

### new features

- [ ] ~multiple pipes in one block ?~

**Comment by bocik1** [comment]
a

**Comment by TheAlaskanPhysicist** [comment]
Here's a list of things I noticed while looking around.
- [ ] Maybe have the multiblock for Boilers cycle through the different materials since they're identical in the Multiblock info.
- [x] Collapse ore blocks into REI categories similar to tools.

**Comment by Irgendwer01** [comment]
> Why have an assembler and a circuit assembler?

@stanieldev It's intended for both to be kept.

> If possible, adding a recipe section for each extruder with a certain mold? It's not 100% needed.

IMO it would clutter JEI/REI/whatever recipe viewers are out there for newer MC versions very much.

**Comment by screret** [comment]
- [x] Robot arm cover

**Comment by Hexasphere0** [comment]
Some more things I noticed that are missing:
- [x] ~~Wetware recipes~~
- [x] ~~Oil recipes~~
- [x] Drill
- [x] Solar panels (as a cover)
- [x] Ore processing jei page
- [x] Terminal
- [x] Cetane boosted diesel
- [x] High octane gasoline
- [x] Rename plastic plates to sheets and foils to thin sheets, like in 1.12?
- [-] ~~Crafting station~~
- [x] Tooltips for coil temperature

**Comment by serenibyss** [comment]
Any missing recipes should be present in code, but commented out due to things previously missing (such as cleanroom, assembly line, fusion etc.). Wetware should be that way as well

**Comment by 34486** [comment]
- [x] Mining hammer 
- [x] a power drill? 

- [x] Correct/update/add tooltips for wires and pipes I think need done?

**Comment by h3tR** [comment]
Might want to add the 1.12 2.7 features?

**Comment by stanieldev** [comment]
Could we have ores matched under REI so that it has the thing that the tools have?
I think it would be nicer for the GUI.

**Comment by screret** [comment]
# 2.7 CONTENT

- [x] Computation
- [x] recipeviewer pages for ores/fluids/etc
- [x] HPCA
- [x] Research Station
- [x] Power Substation
- [x] Lasers
- [x] Active Transformer
- [x] ghost circuits in input buses
- [x] ME hatch/bus
- [x] Long-Distance pipes

- [x] config option to remove vanilla ores? (can be "add this datapack")
- [ ] maintenance rebalance
- [x] add minimap integration to prospector
- [x] item magnets
- [ ] lasers in assembly lines (https://github.com/GregTechCEu/GregTech/pull/462)

**Comment by h3tR** [comment]
- [x] Tree felling behaviour for GT axes

**Comment by nekomaster** [comment]
- [x] Deepslate (and tuff?) ore generation

**Comment by mikerooni** [comment]
### Covers:

- [x] Robot Arm (#192)
- [x] Detectors (#214)
- [x] Machine Controller (#236)
- [x] Computer Monitor (#236)
- [x] Item Voiding (#249)
- [x] Fluid Regulator (#272)
- [x] Fluid Voiding (#272)
- [ ] Ender Fluid Link (#328)
- [x] Shutter Module

Not to be ported:
- Digital Interface
- Crafting Table

**Comment by lukaslcf** [comment]
- [x] Item pipes

**Comment by stanieldev** [comment]
# Exhaustive List of Discovery Part 1

### Liquid/Gas Buckets
- [ ] Add Tag `#ae2:p2p_attunements/fluid_p2p_tunnel` for liquid attunement
- [ ] Hide buckets from JEI/REI/EMI since fluids achieve the same effect

### Coke Oven Bricks [Block]
- [ ] Remove Tag `#forge:mineable/Wrench`
- [ ] Add Tag `#forge:storage_blocks/coke_oven_brick`
- [ ] Consider Slabs, Fences, Walls, and Stairs

### Firebricks [Block]
- [ ] Remove Tag `#forge:mineable/Wrench`
- [ ] Add Tag `#forge:storage_blocks/firebrick`
- [ ] Add compression recipe : `4 firebrick -> 1 firebricks`
- [ ] Consider Slabs, Fences, Walls, and Stairs

### Nether Bricks [Block]
- [ ] Add Tag `#forge:storage_blocks/nether_brick`

### Steam Machine Casing
- [ ] Perhaps switch normal bricks for firebricks

### Tempered Glass
- [ ] It is easier and faster to make in the Arc furnace, so blast furnace recipe is unnecessary
- [ ] Remove Tag `#forge:mineable/Wrench`

### Assembly Line Grating
- [ ] Add assembler recipe with same or less items

### Assembly Line Casing
- [ ] Add assembler recipe with same or less items

### Assembly Line Unit
- [ ] Add assembler recipe with same or less items

### Laminated Glass
- [ ] Remove Tag `#forge:mineable/Wrench`

### Steel Turbine Casing
- [ ] Change color to match Magnalium
- [ ] Change name to `Magnalium Turbine Casing`

### PTFE Pipe Casing
- [ ] Change name to `PTFE Pipe Casing` (ptfe is lowercase as of now)

## Hermetic Casings
- [ ] Change names to use voltage levels instead of roman numerals
- [ ] Give Hermetic Casing II a recipe
- [ ] Give Hermetic Casings an assembler recipe

## Engine Intakes
- [ ] Give Engine Intakes an assembler recipe

### Fusion Glass
- [ ] Remove Tag `#forge:mineable/Wrench`

### Cleanroom Glass
- [ ] Remove Tag `#forge:mineable/Wrench`

### Plascrete
- [ ] Remove Tag `#forge:mineable/Wrench`

### Filter Casing
- [ ] Add assembler recipe with same or less items

### Sterilizing Filter Casing
- [ ] Add assembler recipe with same or less items

## Fireboxes
- [ ] Give Fireboxes an assembler recipe

### Rubber Log
- [ ] Add Tag `#minecraft:logs_that_burn`
- [ ] Add Tag `#gtceu:rubber_logs`
- [ ] Add Tag `#minecraft:overworld_natural_logs`
- [ ] Consider adding stripped wood and 6-sided varients

**Comment by Rundas01** [comment]
- [x] Making pipes one-directional with a wrench on shiftclick

**Comment by screret** [comment]
- [ ] add a toolbox (?)

**Comment by MasterSparkInYourFace** [comment]
- [-] ~~Crafting recipes for bedrock ore miners when enabled?~~

**Comment by screret** [comment]
> - [ ] Crafting recipes for bedrock ore miners when enabled?

IMO that's DIY for the packmaker to do.

**Comment by MasterSparkInYourFace** [comment]
> IMO that's DIY for the packmaker to do.

in that case, how do I add assembler recipes via datapack?

**Comment by DancingSnow0517** [comment]
- [-] ~~add wireless energy hatch (?)~~

**Comment by Irgendwer01** [comment]
> > * [ ]  Crafting recipes for bedrock ore miners when enabled?
> 
> IMO that's DIY for the packmaker to do.

If it's an standard machine for CEu modern, it should have an recipe IMO.

**Comment by Irgendwer01** [comment]
> > IMO that's DIY for the packmaker to do.
> 
> in that case, how do I add assembler recipes via datapack?

Why not just use KubeJS?

**Comment by DancingSnow0517** [comment]
> > > IMO that's DIY for the packmaker to do.
> > 
> > 
> > in that case, how do I add assembler recipes via datapack?
> 
> Why not just use KubeJS?

how to add some GT recipes use KubeJS? I don't understand how to write it....

**Comment by mikerooni** [comment]
### Decorative Blocks:

- [x] Lamps
- [x] Hazard Signs & Stripes
- [x] Rubber Wood / Treated Wood blocks (Doors, Slabs, Stairs, Fences, Gates)

#### Stone Variants:

***Types:***
- [-] Black Granite
- [x] Red Granite
- [x] Marble
- [-] Basalt (?)
- [x] Light Concrete
- [x] Dark Concrete

***Variants:***
- [x] Regular
- [x] Mossy
- [x] Polished
- [x] Bricks
- [x] Cracked Bricks
- [x] Mossy Bricks
- [x] Chiseled
- [x] Tiles
- [x] Small Tiles
- [x] Small Bricks
- [x] Windmill Tiles (A / B)
- [x] Square Bricks

**Comment by VaroxF7** [comment]
- [x] Void Miner

**Comment by Irgendwer01** [comment]
* [ ]  GCY:L Content :trollface:

**Comment by CactusCool** [comment]
- [ ] Copy-paste feature for stocking busses 
- [x] Autopull mode for stocking busses/hatches to automatically pull items/fluids from connected network

**Comment by Ghidhor** [comment]
[ ] 2.8 content
[ ] MA and prodbees support maybe?

**Comment by Ghidhor** [comment]
[  ] particle accelerators

**Comment by phrostt** [comment]
Smart filter from gtce

**Comment by marisathewitch** [comment]
Re-check colorcodes and color names for blocks.
Example: 
Diode block using full color name. 
Muffler block using voltage only colorname

**Comment by StellaBiscuit** [comment]
> > > IMO that's DIY for the packmaker to do.
> > 
> > 
> > in that case, how do I add assembler recipes via datapack?
> 
> Why not just use KubeJS?

Here is 5 reasons why it would be great to have datapack support on top of KJS

1 - (Almost) Every mods that has recipes uses datapack as it is the standard Mojang used themselves, having to use a different format for that mod in particular can feel weird for people that aren't used to it
2 - Removes the necessity of KubeJS to add/remove recipes, it will also prevent the following
 - You never know when a mod just dies out of nowhere when a new version pops up
 - If KubeJS doesn't update in time (which is likely due to the nature of the mod), you cannot change recipes until the update is out

3 - It is way easier to change recipes with datapack then with KubeJS as you only need to put the recipe at the same location in the custom datapack and boom, recipe is changed while KubeJS requires to both remove then add the new recipes
4 - Datapack format doesn't require to know codding at all as it is just a take values then plugging them in while KubeJS can be somewhat hard to understand when first used (especially since newer version removed the example script and replaced them with empty scripts instead)
5 - Since the default recipes are inside the jar file, you get a buck load of example for the players to use without needing to do documentation like KubeJS integration

Also, I will point out that I said "On top of KJS" and not "Better then KJS", KubeJS is an amazing tool once you get the hang of it, but it is undeniable that, for recipes at least, datapacks are really valuable if you know what you are doing.
They both have their pros and cons and not being able to use both really annoys me personally (especially the "modify recipes quickly" part of datapacks that KJS lacks)

Edit: changed a few things

**Comment by Drackion** [comment]
@TBiscuit1 GTCEuM already supports datapacks tho i would say the easiest way to see them is with kubejs and probejs,

gtceum just doesn't use datapack recipes itself

**Comment by StellaBiscuit** [comment]
> @TBiscuit1 GTCEuM already supports datapacks tho i would say the easiest way to see them is with kubejs and probejs,
> 
> gtceum just doesn't use datapack recipes itself

_Why tho_ that removes the whole point and advantage of having datapack support for modpack makers, easy change, no documentation needed and no other mods being required

**Comment by screret** [comment]
> _Why tho_ that removes the whole point and advantage of having datapack support for modpack makers, easy change, no documentation needed and no other mods being required

we support datapacks. 
We don't bundle the recipes _by default_, because that'd bloat the filesize 20x. you can enable the `dumpRecipes` config option to get the recipe JSONs if you so wish. even though prototyping would be significantly faster with KJS.

**Comment by MaxNeedsSnacks** [comment]
> 3 - It is way easier to change recipes with datapack then with KubeJS as you only need to put the recipe at the same location in the custom datapack and boom, recipe is changed while KubeJS requires to both remove then add the new recipes

You... can also just set the recipe id with KubeJS and it'll replace any existing recipe with the same ID? I'm confused...

**Comment by screret** [comment]
> Re-check colorcodes and color names for blocks. Example: Diode block using full color name. Muffler block using voltage only colorname

make a new issue please.

**Comment by TheFlames096** [comment]
So are we going to add small ores？
Also there should be a map mod like xearos map ore vein support

**Comment by SasB18** [comment]
- [ ] Nanosuit, Quantumsuit (?)

**Comment by edshPC** [comment]
Long term suggestion:
- [ ] Ad Astra integration to make hi-tier veins generate on different planets (if mod installed) as well as changing rockets and fuel recipies to relate with GT tiers similar to how its done in GT new horizons

**Comment by screret** [comment]
> Long term suggestion:
> 
> * [ ]  Ad Astra integration to make hi-tier veins generate on different planets (if mod installed) as well as changing rockets and fuel recipies to relate with GT tiers similar to how its done in GT new horizons

I have a space mod specifically designed as a GT addon :)

**Comment by marlonus** [comment]
we need the fancy effects.. I am not a coder, and this may be unnecessary, but hell they look fabulous.

**Comment by TheAlaskanPhysicist** [comment]
> we need the fancy effects.. I am not a coder, and this may be unnecessary, but hell they look fabulous.

If you're willing to work on it, I would be willing to review it.
Depending on the spirit of the game, might want to make it an addon instead.

**Comment by 34486** [comment]
> we need the fancy effects.. I am not a coder, and this may be unnecessary, but hell they look fabulous.

This can be done through KubeJS though can't it? Just throwing that out there as a maybe and for future reference?

**Comment by Miner239** [comment]
* [ ] Food centrifuging

**Comment by touhumk9** [comment]
Is it possible to revert to the conventional 3×3chunk generation of iron, copper, and tin veins? At least the way it is generated now is not interesting

**Comment by auroraanna** [comment]
- [ ] flesh out wiki

**Comment by Praetorian6478** [comment]
Referring to @Miner239-s suggestion, adding some growable resources centrifuging into Methane Gas, as a pretty good source of energy in the early-game (Small Gas Turbines first, bigger ones in the HV+ tier). Used to make it till the EV with setups on Melon centrifuging, using GT5u and IC2 back then.
Glory to the BioIndustries!

**Comment by Daeaiones** [comment]
Understandable if off topic, is there a chance of getting a page dedicated to where the community would suggest machines to go in voltage tiers to help mod cross support?

**Comment by JuiceyBeans** [comment]
> Understandable if off topic, is there a chance of getting a page dedicated to where the community would suggest machines to go in voltage tiers to help mod cross support?

Machines for cross compat falls into addon/pack dev territory, and will most likely not be implemented in the base mod

**Comment by sovietwankle-web** [comment]
what about nuclear electric

**Comment by Krocceto** [comment]
WHAT do you mean by "Magic Energy"?

**Comment by Ghostipedia** [comment]
Pleas Stop commenting on this issue, Going to lock it as this is a stale/old/outdated todo
